logging:
  level:
    root: INFO
server:
  port: ${PORT}
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
      
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  data:
    rest:
      base-path: /api

    
