logging:
  level:
    root: INFO
server:
  port: 8080
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://ec2-54-243-147-162.compute-1.amazonaws.com:5432/da1j5db88nrhj6
    username: cersmvihkutcja
    password: 49020d475f44898ecb7a86ea907ffe3d43182f6996166d57b022ec21d83048bd
    driver-class-name: org.postgresql.Driver

    
